version: '3.7'

services:
  dev:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.5
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start
    ports:
      - 8111:5000
    environment:
      PASS: ${PASS}
      MAIL: ${MAIL}
      HOST: ${HOST}
    networks:
      - nesjs-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  nesjs-network:
